server:
  port: 8008
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: pmp
  http:
    encoding:
      force: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    name: datasource
    url: jdbc:p6spy:mysql://192.168.1.91:3530/pmp?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: JHN2rggf2345gff2gFde
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cict.pmp.entity
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml